export const EMPLOYMENT_TYPE = [
  "Full-time",
  "Part-time",
  "Casual",
  "Contract",
  "Apprenticeship",
  "Traineeship",
  "Employment on commission",
  "Probation",
];

export const CAREER_LEVEL = [
  "Student/Internship",
  "Entry level",
  "Experience",
  "Team leader",
  "Manager",
];

export const PROVINCE_CITY = [
  "An Giang",
  "Kon Tum",
  "Bà Rịa – Vũng Tàu",
  "Lai Châu",
  "Bắc Giang",
  "Lâm Đồng",
  "Bắc Kạn",
  "Lạng Sơn",
  "Bạc Liêu",
  "Lào Cai",
  "Bắc Ninh",
  "Long An",
  "Bến Tre",
  "Nam Định",
  "Bình Định",
  "Nghệ An",
  "Bình Dương",
  "Ninh Bình",
  "Bình Phước",
  "Ninh Thuận",
  "Bình Thuận",
  "Phú Thọ",
  "Cà Mau",
  "Phú Yên",
  "Cần Thơ",
  "Quảng Bình",
  "Cao Bằng",
  "Quảng Nam",
  "Đà Nẵng",
  "Quảng Ngãi",
  "Đắk Lắk",
  "Quảng Ninh",
  "Đắk Nông",
  "Quảng Trị",
  "Điện Biên",
  "Sóc Trăng",
  "Đồng Nai",
  "Sơn La",
  "Đồng Tháp",
  "Tây Ninh",
  "Gia Lai",
  "Thái Bình",
  "Hà Giang",
  "Thái Nguyên",
  "Hà Nam",
  "Thanh Hóa",
  "Hà Nội",
  "Thừa Thiên Huế",
  "Hà Tĩnh",
  "Tiền Giang",
  "Hải Dương",
  "TP Hồ Chí Minh",
  "Hải Phòng",
  "Trà Vinh",
  "Hậu Giang",
  "Tuyên Quang",
  "Hòa Bình",
  "Vĩnh Long",
  "Hưng Yên",
  "Vĩnh Phúc",
  "Khánh Hòa",
  "Yên Bái",
  "Kiên Giang",
];

export const CURRENCY_OPTION = [
  {
    locale: "de-DE",
    currency: "EUR",
  },
  {
    locale: "en-US",
    currency: "USD",
  },
  {
    locale: "en-GB",
    currency: "GBP",
  },
  {
    locale: "ja-JP",
    currency: "JPY",
  },
  {
    locale: "en-IN",
    currency: "INR",
  },
  {
    locale: "vi-VN",
    currency: "VND",
  },
];
